### ISSUE TITLE
使用主题后，点击文章会在新标签页中打开，如何在当前页面打开

### ISSUE THREAD

**Issue by MaloneQQ** [chenjiayin1990/ghost-matery#1]
首先，非常感谢作者提供matery主题，非常漂亮。

使用中遇到问题：
使用主题后，点击文章会在新标签页中打开，如何在当前页面打开

希望可以帮忙解决，万分感谢！

**Comment by GrayLiu** [comment]
主题在显示文章的时候不支持 markdown 格式么

**Comment by blinkfox** [comment]
@MaloneQQ  不好意思，才看到
解决方法：在项目`partials/loop.hbs`文件中第三行去掉`target="_blank"`就行，就不会在新标签页中打开了

**Comment by blinkfox** [comment]
@GrayLiu 
支持的额！
